server:
    port: 8080

spring:
    application:
        name: file_crud

    datasource:
        url: jdbc:mysql://localhost:3306/file_crud_db?useSSL=false&serverTimezone=Asia/Seoul
        username: root
        password: c0ding_gw4n9
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: update # (create, update, validate, none 중 택1)
        show-sql: true
        properties:
            hibernate:
                "[format_sql]": true

    servlet:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB

file:
    location:
        upload-path: C:\Users\LG\Visual Studio Code\java projects\ziindrive\src\main\resources\static\uploads
        bin-path: C:\Users\LG\Visual Studio Code\java projects\ziindrive\src\main\resources\static\trashbin
